ISSUE #155: useQuorum parameters added to check if quorum is enabled/…
piraeusdatastore/linstor-csi pull request #163
Opened 2022-05-12 11:10 UTC by tw185112

…disabled to stop volume attachments from failing

Signed-off-by: Tom Wilson <thomas.wilson@ncr.com>

2022-05-12 12:27 UTC, WanzenBug requested changes
Please see that https://github.com/piraeusdatastore/linstor-csi/pull/163/checks pass.

Also some cleanup/simplification is needed. The logic change itself seems sound.

2022-05-12 12:27 UTC, WanzenBug commented on pkg/client/linstor.go
> +		useQuorum := volQuorum || controllerQuorum
We don't need to check the controller properties here. 

First of all we would also need to check the resource group property.

Secondly, this setting does not influence _existing_ resources, so only whatever is set directly on the resource definition is relevant.

So: just remove this and use `volQuorum` directly.

2022-05-12 12:27 UTC, WanzenBug commented on pkg/client/linstor.go
> +		UseQuorum:     quorum,
```suggestion
		UseQuorum:     resDef.Props["DrbdOptions/Resource/quorum"] != "off",
```

2022-05-12 14:01 UTC, WanzenBug approved these changes
LGTM. I'll run some e2e tests on this, but I don't expect any issues.

2022-05-12 14:14 UTC, rck commented
@WanzenBug you squash it before merging, right?

2022-05-13 07:55 UTC, merged

2022-05-13 07:56 UTC, WanzenBug commented
@tw185112 thank you for your contribution!