Support live-migration with allow-two-primaries
piraeusdatastore/linstor-csi pull request #177
Opened 2022-11-02 11:35 UTC by kvaps

This PR allows to live-migrate KubeVirt virtual machines by setting `allow-two-primaries` flag dynamically.

fixes https://github.com/piraeusdatastore/linstor-csi/issues/159

## Changes in this PR:

* **controllerPublishVolume:**
    * if volume has `type: Block` and `accessMode: ReadWriteMany`;
    * if it is already `InUse` at one other node;
    
   enables `allow-two-primaries` flag

* **controllerUnpublishVolume:**
  * if volume `InUse` at one one less amount of nodes

  removes `allow-two-primaries` flag

2022-11-02 12:25 UTC, WanzenBug requested changes
Change looks good, just need to fix `pkg/client/linstor_test.go` to use the extra argument on `Attach()`

2022-11-03 11:15 UTC, WanzenBug commented
@kvaps If you want, I can take care of the tests + lints

2022-11-03 12:00 UTC, kvaps commented
Sure, tests are fixed

2022-11-03 12:11 UTC, WanzenBug approved these changes
I'll just quickly start the e2e test suite, then we can merge this

2022-11-03 12:31 UTC, WanzenBug commented on pkg/client/linstor.go
> +	if err != nil {
```suggestion
	if nil404(err) != nil {
```

Otherwise we fail the CSI tests because a "double" delete will result in an error

2022-11-03 12:32 UTC, WanzenBug commented on pkg/client/linstor.go
> +	if err != nil {
Or actually just `return nil404(err)` in the branch

2022-11-03 14:22 UTC, merged

2022-11-03 14:22 UTC, WanzenBug commented
Thanks!